// The buildInfo constant is generated by sbt. Do not edit directly.
// TODO set this up
// const buildInfo = { organization: 'com.ovoenergy', moduleName: 'dynosaur', latestVersion: '0.0.1', scalaMinorVersion: '2.12', scalaPublishVersions: '2.11 and 2.12' };

const repoUrl = "https://github.com/ovotech/dynosaur";

// See https://docusaurus.io/docs/site-config for available options.
const siteConfig = {
  title: 'Dynosaur',
  tagline: 'Purely functional, native DynamoDb client based on FS2',
  url: 'https://ovotech.github.io/dynosaur',
  baseUrl: '/dynosaur/',

  customDocsPath: 'dynosaur-docs/target/mdoc',

  projectName: 'dynosaur',
  organizationName: 'ovotech',

  headerLinks: [
    { doc: 'schema', label: 'Documentation' },
    { href: repoUrl, label: "GitHub" }
  ],

  // headerIcon: 'img/fs2-kafka.white.svg',
  // titleIcon: 'img/fs2-kafka.svg',
  // favicon: 'img/favicon.png',

  colors: {
    primaryColor: '#122932',
    secondaryColor: '#153243',
  },

  copyright: `Copyright © 2018-${new Date().getFullYear()} OVO Energy Limited.`,

  highlight: { theme: 'github' },

  onPageNav: 'separate',

  cleanUrl: true,

  // buildInfo,
    
  repoUrl
};

module.exports = siteConfig;
